# Generated by Django 3.2.9 on 2021-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.DateField(blank=True, null=True)),
                ('vehical_No', models.CharField(blank=True, max_length=8, null=True)),
                ('party_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('container_No', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('from_One', models.CharField(blank=True, max_length=250, null=True)),
                ('uploading', models.CharField(blank=True, max_length=250, null=True)),
                ('to_One', models.CharField(blank=True, max_length=250, null=True)),
                ('to_Two', models.CharField(blank=True, max_length=250, null=True)),
                ('bill_No', models.CharField(blank=True, max_length=250, null=True)),
                ('bill_Amt', models.PositiveBigIntegerField(blank=True, null=True)),
                ('advance', models.PositiveBigIntegerField(blank=True, null=True)),
                ('balance', models.PositiveBigIntegerField(blank=True, null=True)),
                ('detain_Day', models.CharField(blank=True, max_length=250, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('inserted_On', models.DateTimeField(auto_now_add=True)),
                ('updated_On', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DRS',
                'verbose_name_plural': 'DRS Report',
                'ordering': ['-id'],
            },
        ),
    ]
